[build]
builder = "DOCKERFILE"

# Installa le dipendenze e costruisci Angular
buildCommand = "npm install && npm run build"

staticBuild = false

# Usa il percorso corretto in base al nome del progetto in angular.json
staticPublishPath = "dist/ng-habado"

[static]
# Serve index.html per tutte le rotte Angular (SPA)
rewrite = "index.html"

[build.env]
# Versione Node LTS compatibile con Angular
NODE_VERSION = "22.16"


[deploy]
port = 3000